# Generated by Django 5.0.14 on 2026-05-29 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Started', 'Started'), ('Ready', 'Ready'), ('Partial Delivery', 'Partial Delivery'), ('Delivered', 'Delivered')], default='Booked', max_length=20)),
                ('delivery_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('priority', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'indexes': [models.Index(fields=['user', 'status'], name='orders_user_id_17dbdf_idx'), models.Index(fields=['user', 'delivery_date'], name='orders_user_id_0931ad_idx'), models.Index(fields=['customer'], name='orders_custome_6c3a7f_idx')],
            },
        ),
    ]
