# Generated by Django 5.0.14 on 2026-06-03 03:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('order_created', 'Order Created'), ('status_changed', 'Status Changed'), ('delivery_marked', 'Delivery Marked'), ('partial_delivery', 'Partial Delivery'), ('installment_created', 'Installment Created'), ('installment_paid', 'Installment Paid'), ('payment_updated', 'Payment Updated')], max_length=30)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='orders.order')),
            ],
            options={
                'db_table': 'order_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
