# Generated by Django 5.0.14 on 2026-06-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_backfill_delivered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderactivity',
            name='activity_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_deleted', 'Order Deleted'), ('status_changed', 'Status Changed'), ('delivery_marked', 'Delivery Marked'), ('partial_delivery', 'Partial Delivery'), ('installment_created', 'Installment Created'), ('installment_paid', 'Installment Paid'), ('payment_updated', 'Payment Updated')], max_length=30),
        ),
    ]
