# Generated by Django 5.0.14 on 2026-05-30 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=500, unique=True)),
                ('public_url', models.URLField(max_length=1000)),
                ('photo_type', models.CharField(choices=[('garment', 'Garment'), ('notes', 'Notes')], max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.order')),
            ],
            options={
                'db_table': 'order_photos',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
